export interface CityOption {
  id: string;
  label: string;
  secondary?: string;
  aliases?: string[];
}

function mk(label: string, secondary: string, aliases?: string[]): CityOption {
  return {
    id: label.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, ""),
    label,
    secondary,
    ...(aliases ? { aliases } : {}),
  };
}

const PUNJAB = [
  mk("Lahore", "Punjab"),
  mk("Faisalabad", "Punjab", ["Lyallpur"]),
  mk("Rawalpindi", "Punjab"),
  mk("Gujranwala", "Punjab"),
  mk("Multan", "Punjab"),
  mk("Bahawalpur", "Punjab"),
  mk("Sargodha", "Punjab"),
  mk("Sialkot", "Punjab"),
  mk("Sheikhupura", "Punjab"),
  mk("Rahim Yar Khan", "Punjab", ["RYK"]),
  mk("Jhang", "Punjab"),
  mk("Gujrat", "Punjab"),
  mk("Kasur", "Punjab"),
  mk("Sahiwal", "Punjab", ["Montgomery"]),
  mk("Okara", "Punjab"),
  mk("Wah Cantt", "Punjab", ["Wah"]),
  mk("Dera Ghazi Khan", "Punjab", ["DG Khan"]),
  mk("Chiniot", "Punjab"),
  mk("Kamoke", "Punjab"),
  mk("Hafizabad", "Punjab"),
  mk("Burewala", "Punjab"),
  mk("Khanewal", "Punjab"),
  mk("Muzaffargarh", "Punjab"),
  mk("Mandi Bahauddin", "Punjab", ["MB Din"]),
  mk("Jhelum", "Punjab"),
  mk("Chakwal", "Punjab"),
  mk("Attock", "Punjab", ["Campbellpur"]),
  mk("Vehari", "Punjab"),
  mk("Muridke", "Punjab"),
  mk("Bahawalnagar", "Punjab"),
  mk("Kot Addu", "Punjab"),
  mk("Gojra", "Punjab"),
  mk("Daska", "Punjab"),
  mk("Mianwali", "Punjab"),
  mk("Pakpattan", "Punjab"),
  mk("Toba Tek Singh", "Punjab", ["TT Singh"]),
  mk("Jaranwala", "Punjab"),
  mk("Layyah", "Punjab"),
  mk("Lodhran", "Punjab"),
  mk("Bhakkar", "Punjab"),
  mk("Rajanpur", "Punjab"),
  mk("Khushab", "Punjab", ["Jauharabad"]),
  mk("Nankana Sahib", "Punjab"),
  mk("Narowal", "Punjab"),
  mk("Chishtian", "Punjab"),
  mk("Hasilpur", "Punjab"),
  mk("Kabirwala", "Punjab"),
  mk("Arifwala", "Punjab"),
  mk("Sadiqabad", "Punjab"),
  mk("Haroonabad", "Punjab"),
  mk("Ahmadpur East", "Punjab", ["Ahmedpur East"]),
  mk("Liaquatpur", "Punjab"),
  mk("Shujaabad", "Punjab"),
  mk("Jalalpur Jattan", "Punjab"),
  mk("Kharian", "Punjab"),
  mk("Sarai Alamgir", "Punjab"),
  mk("Lalamusa", "Punjab"),
  mk("Dinga", "Punjab"),
  mk("Wazirabad", "Punjab"),
  mk("Nowshera Virkan", "Punjab"),
  mk("Pindi Bhattian", "Punjab"),
  mk("Sillanwali", "Punjab"),
  mk("Bhalwal", "Punjab"),
  mk("Shahkot", "Punjab"),
  mk("Chichawatni", "Punjab"),
  mk("Mian Channu", "Punjab"),
  mk("Renala Khurd", "Punjab"),
  mk("Depalpur", "Punjab"),
  mk("Chunian", "Punjab"),
  mk("Pattoki", "Punjab"),
  mk("Raiwind", "Punjab"),
  mk("Kamalia", "Punjab"),
  mk("Pir Mahal", "Punjab"),
  mk("Kot Momin", "Punjab"),
  mk("Talagang", "Punjab"),
  mk("Pind Dadan Khan", "Punjab"),
  mk("Hasan Abdal", "Punjab"),
  mk("Hazro", "Punjab"),
  mk("Fateh Jang", "Punjab"),
  mk("Jand", "Punjab"),
  mk("Pindi Gheb", "Punjab"),
  mk("Kallar Kahar", "Punjab"),
  mk("Choa Saidan Shah", "Punjab"),
  mk("Ferozewala", "Punjab"),
  mk("Jampur", "Punjab"),
  mk("Taunsa", "Punjab"),
  mk("Kot Radha Kishan", "Punjab"),
  mk("Zahir Pir", "Punjab"),
  mk("Khanpur", "Punjab"),
  mk("Fort Abbas", "Punjab"),
  mk("Minchinabad", "Punjab"),
  mk("Yazman", "Punjab"),
  mk("Jahanian", "Punjab"),
  mk("Tandlianwala", "Punjab"),
  mk("Samundri", "Punjab"),
  mk("Gojra", "Punjab"),
  mk("Kot Abdul Malik", "Punjab"),
  mk("Shahdara", "Punjab"),
  mk("Dijkot", "Punjab"),
  mk("Shahpur", "Punjab"),
  mk("Bhera", "Punjab"),
  mk("Sangla Hill", "Punjab"),
  mk("Safdarabad", "Punjab"),
  mk("Ferozewala", "Punjab"),
  mk("Kanganpur", "Punjab"),
  mk("Malakwal", "Punjab"),
  mk("Phalia", "Punjab"),
  mk("Qadirpur Ran", "Punjab"),
  mk("Shorkot", "Punjab"),
  mk("Ahmadpur Sial", "Punjab"),
  mk("Alipur", "Punjab"),
  mk("Jatoi", "Punjab"),
  mk("Karor Lal Esan", "Punjab"),
  mk("Chaubara", "Punjab"),
  mk("Fazilpur", "Punjab"),
  mk("Kot Chutta", "Punjab"),
  mk("Dunyapur", "Punjab"),
  mk("Mailsi", "Punjab"),
  mk("Kehror Pakka", "Punjab"),
  mk("Dera Nawab Sahib", "Punjab"),
  mk("Uch Sharif", "Punjab"),
  mk("Khairpur Tamewali", "Punjab"),
  mk("Chowk Azam", "Punjab"),
  mk("Murree", "Punjab"),
  mk("Kotli Sattian", "Punjab"),
  mk("Gujar Khan", "Punjab"),
  mk("Kahuta", "Punjab"),
  mk("Taxila", "Punjab"),
  mk("Kallar Syedan", "Punjab"),
  mk("Daultala", "Punjab"),
];

const SINDH = [
  mk("Karachi", "Sindh"),
  mk("Hyderabad", "Sindh"),
  mk("Sukkur", "Sindh"),
  mk("Larkana", "Sindh"),
  mk("Nawabshah", "Sindh", ["Shaheed Benazirabad"]),
  mk("Mirpur Khas", "Sindh"),
  mk("Jacobabad", "Sindh"),
  mk("Shikarpur", "Sindh"),
  mk("Khairpur", "Sindh"),
  mk("Dadu", "Sindh"),
  mk("Tando Adam", "Sindh"),
  mk("Tando Allahyar", "Sindh"),
  mk("Tando Muhammad Khan", "Sindh"),
  mk("Badin", "Sindh"),
  mk("Thatta", "Sindh"),
  mk("Sujawal", "Sindh"),
  mk("Umerkot", "Sindh", ["Amarkot"]),
  mk("Ghotki", "Sindh"),
  mk("Kandhkot", "Sindh"),
  mk("Kashmore", "Sindh"),
  mk("Naushahro Feroze", "Sindh"),
  mk("Moro", "Sindh"),
  mk("Kambar", "Sindh", ["Qambar"]),
  mk("Shahdadkot", "Sindh"),
  mk("Ratodero", "Sindh"),
  mk("Sanghar", "Sindh"),
  mk("Mithi", "Sindh"),
  mk("Matiari", "Sindh"),
  mk("Hala", "Sindh"),
  mk("Sehwan", "Sindh"),
  mk("Rohri", "Sindh"),
  mk("Pano Aqil", "Sindh"),
  mk("Daharki", "Sindh"),
  mk("Mirpur Mathelo", "Sindh"),
  mk("Ubauro", "Sindh"),
  mk("Digri", "Sindh"),
  mk("Kunri", "Sindh"),
  mk("Jamshoro", "Sindh"),
  mk("Kotri", "Sindh"),
  mk("Gambat", "Sindh"),
  mk("Kot Diji", "Sindh"),
  mk("Nasirabad", "Sindh"),
  mk("Mehrabpur", "Sindh"),
  mk("Bhiria", "Sindh"),
  mk("Khipro", "Sindh"),
  mk("Tando Ghulam Ali", "Sindh"),
  mk("Golarchi", "Sindh"),
  mk("Talhar", "Sindh"),
  mk("Keti Bandar", "Sindh"),
  mk("Mirpur Bathoro", "Sindh"),
  mk("Warah", "Sindh"),
  mk("Dokri", "Sindh"),
  mk("Garhi Khairo", "Sindh"),
  mk("Thari Mirwah", "Sindh"),
  mk("Chachro", "Sindh"),
  mk("Islamkot", "Sindh"),
  mk("Diplo", "Sindh"),
];

const KP = [
  mk("Peshawar", "Khyber Pakhtunkhwa"),
  mk("Mardan", "Khyber Pakhtunkhwa"),
  mk("Mingora", "Khyber Pakhtunkhwa", ["Swat"]),
  mk("Abbottabad", "Khyber Pakhtunkhwa"),
  mk("Kohat", "Khyber Pakhtunkhwa"),
  mk("Bannu", "Khyber Pakhtunkhwa"),
  mk("Dera Ismail Khan", "Khyber Pakhtunkhwa", ["DI Khan"]),
  mk("Nowshera", "Khyber Pakhtunkhwa"),
  mk("Charsadda", "Khyber Pakhtunkhwa"),
  mk("Mansehra", "Khyber Pakhtunkhwa"),
  mk("Swabi", "Khyber Pakhtunkhwa"),
  mk("Haripur", "Khyber Pakhtunkhwa"),
  mk("Batkhela", "Khyber Pakhtunkhwa", ["Malakand"]),
  mk("Timergara", "Khyber Pakhtunkhwa", ["Lower Dir"]),
  mk("Dir", "Khyber Pakhtunkhwa", ["Upper Dir"]),
  mk("Chitral", "Khyber Pakhtunkhwa"),
  mk("Hangu", "Khyber Pakhtunkhwa"),
  mk("Karak", "Khyber Pakhtunkhwa"),
  mk("Lakki Marwat", "Khyber Pakhtunkhwa"),
  mk("Tank", "Khyber Pakhtunkhwa"),
  mk("Buner", "Khyber Pakhtunkhwa", ["Daggar"]),
  mk("Shangla", "Khyber Pakhtunkhwa", ["Alpuri"]),
  mk("Battagram", "Khyber Pakhtunkhwa"),
  mk("Torghar", "Khyber Pakhtunkhwa"),
  mk("Kohistan", "Khyber Pakhtunkhwa", ["Dassu"]),
  mk("Kulachi", "Khyber Pakhtunkhwa"),
  mk("Paharpur", "Khyber Pakhtunkhwa"),
  mk("Pabbi", "Khyber Pakhtunkhwa"),
  mk("Risalpur", "Khyber Pakhtunkhwa"),
  mk("Takht Bhai", "Khyber Pakhtunkhwa"),
  mk("Shabqadar", "Khyber Pakhtunkhwa"),
  mk("Tangi", "Khyber Pakhtunkhwa"),
  mk("Lachi", "Khyber Pakhtunkhwa"),
  mk("Havelian", "Khyber Pakhtunkhwa"),
  mk("Ghazi", "Khyber Pakhtunkhwa"),
  mk("Balakot", "Khyber Pakhtunkhwa"),
  mk("Oghi", "Khyber Pakhtunkhwa"),
  mk("Cherat", "Khyber Pakhtunkhwa"),
  mk("Jamrud", "Khyber Pakhtunkhwa", ["Khyber"]),
  mk("Landi Kotal", "Khyber Pakhtunkhwa"),
  mk("Parachinar", "Khyber Pakhtunkhwa", ["Kurram"]),
  mk("Miran Shah", "Khyber Pakhtunkhwa", ["North Waziristan"]),
  mk("Wana", "Khyber Pakhtunkhwa", ["South Waziristan"]),
  mk("Ghalanai", "Khyber Pakhtunkhwa", ["Mohmand"]),
  mk("Khar", "Khyber Pakhtunkhwa", ["Bajaur"]),
  mk("Kalpani", "Khyber Pakhtunkhwa"),
  mk("Utmanzai", "Khyber Pakhtunkhwa"),
  mk("Akora Khattak", "Khyber Pakhtunkhwa"),
  mk("Topi", "Khyber Pakhtunkhwa"),
  mk("Lahor", "Khyber Pakhtunkhwa"),
  mk("Gadoon Amazai", "Khyber Pakhtunkhwa"),
];

const BALOCHISTAN = [
  mk("Quetta", "Balochistan"),
  mk("Gwadar", "Balochistan"),
  mk("Turbat", "Balochistan", ["Kech"]),
  mk("Khuzdar", "Balochistan"),
  mk("Hub", "Balochistan"),
  mk("Chaman", "Balochistan"),
  mk("Sibi", "Balochistan"),
  mk("Zhob", "Balochistan"),
  mk("Loralai", "Balochistan"),
  mk("Dera Murad Jamali", "Balochistan", ["Nasirabad"]),
  mk("Dera Allah Yar", "Balochistan", ["Jafarabad"]),
  mk("Usta Mohammad", "Balochistan"),
  mk("Mastung", "Balochistan"),
  mk("Kalat", "Balochistan"),
  mk("Pishin", "Balochistan"),
  mk("Nushki", "Balochistan"),
  mk("Kharan", "Balochistan"),
  mk("Panjgur", "Balochistan"),
  mk("Dalbandin", "Balochistan", ["Chagai"]),
  mk("Qila Saifullah", "Balochistan"),
  mk("Qila Abdullah", "Balochistan"),
  mk("Muslim Bagh", "Balochistan"),
  mk("Ziarat", "Balochistan"),
  mk("Harnai", "Balochistan"),
  mk("Kohlu", "Balochistan"),
  mk("Dera Bugti", "Balochistan"),
  mk("Barkhan", "Balochistan"),
  mk("Musakhel", "Balochistan"),
  mk("Awaran", "Balochistan"),
  mk("Washuk", "Balochistan"),
  mk("Bela", "Balochistan", ["Lasbela"]),
  mk("Uthal", "Balochistan"),
  mk("Winder", "Balochistan"),
  mk("Sohbatpur", "Balochistan"),
  mk("Jhal Magsi", "Balochistan"),
  mk("Gandava", "Balochistan", ["Kachhi"]),
  mk("Surab", "Balochistan"),
  mk("Mach", "Balochistan"),
  mk("Ormara", "Balochistan"),
  mk("Pasni", "Balochistan"),
  mk("Jiwani", "Balochistan"),
  mk("Duki", "Balochistan"),
];

const ICT = [
  mk("Islamabad", "Islamabad Capital Territory"),
];

const AJK = [
  mk("Muzaffarabad", "Azad Kashmir"),
  mk("Mirpur", "Azad Kashmir"),
  mk("Rawalakot", "Azad Kashmir", ["Poonch"]),
  mk("Kotli", "Azad Kashmir"),
  mk("Bhimber", "Azad Kashmir"),
  mk("Bagh", "Azad Kashmir"),
  mk("Pallandri", "Azad Kashmir", ["Sudhanoti"]),
  mk("Hattian Bala", "Azad Kashmir"),
  mk("Haveli", "Azad Kashmir", ["Forward Kahuta"]),
  mk("Athmuqam", "Azad Kashmir", ["Neelum"]),
  mk("Dadyal", "Azad Kashmir"),
  mk("New Mirpur City", "Azad Kashmir"),
];

const GB = [
  mk("Gilgit", "Gilgit-Baltistan"),
  mk("Skardu", "Gilgit-Baltistan"),
  mk("Chilas", "Gilgit-Baltistan", ["Diamer"]),
  mk("Ghizer", "Gilgit-Baltistan", ["Gakuch"]),
  mk("Astore", "Gilgit-Baltistan"),
  mk("Hunza", "Gilgit-Baltistan", ["Aliabad"]),
  mk("Nagar", "Gilgit-Baltistan"),
  mk("Khaplu", "Gilgit-Baltistan", ["Ghanche"]),
  mk("Shigar", "Gilgit-Baltistan"),
  mk("Kharmang", "Gilgit-Baltistan"),
  mk("Gupis", "Gilgit-Baltistan"),
  mk("Danyore", "Gilgit-Baltistan"),
  mk("Sost", "Gilgit-Baltistan"),
  mk("Karimabad", "Gilgit-Baltistan"),
];

// De-duplicate by id (the Punjab block has a couple of intentional repeats
// while hand-compiling) so the dropdown never shows the same city twice.
const ALL = [...PUNJAB, ...SINDH, ...KP, ...BALOCHISTAN, ...ICT, ...AJK, ...GB];
const seen = new Set<string>();
const deduped = ALL.filter((c) => {
  if (seen.has(c.id)) return false;
  seen.add(c.id);
  return true;
});

// Big metros float to the top of the (otherwise alphabetical) list so the
// most common picks are one glance away when the dropdown opens.
const FEATURED = [
  "karachi", "lahore", "islamabad", "rawalpindi", "faisalabad", "multan",
  "peshawar", "quetta", "gujranwala", "hyderabad", "sialkot", "bahawalpur",
  "sargodha", "sukkur", "abbottabad", "muzaffarabad", "gilgit", "mirpur",
];
const featuredRank = new Map(FEATURED.map((id, i) => [id, i]));

export const PAKISTAN_CITIES: CityOption[] = [...deduped].sort((a, b) => {
  const ra = featuredRank.get(a.id);
  const rb = featuredRank.get(b.id);
  if (ra !== undefined || rb !== undefined) {
    return (ra ?? Number.MAX_SAFE_INTEGER) - (rb ?? Number.MAX_SAFE_INTEGER);
  }
  return a.label.localeCompare(b.label);
});

export function filterCities(query: string): CityOption[] {
  const q = query.trim().toLowerCase();
  if (!q) return PAKISTAN_CITIES;

  return PAKISTAN_CITIES.filter((city) => {
    if (city.label.toLowerCase().includes(q)) return true;
    if (city.secondary && city.secondary.toLowerCase().includes(q)) return true;
    if (city.aliases && city.aliases.some((a) => a.toLowerCase().includes(q))) return true;
    return false;
  });
}
